[server]
maxUploadSize = 500
# cleaner URL handling
enableCORS = false

[theme]
# US Open Blue - Great contrast with white text
primaryColor = "#0065BD"    
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2129"
textColor = "#FAFAFA" 
font = "sans serif"

[client]
# Hides the "Manage App" and developer options for viewers
toolbarMode = "viewer"

[browser]
# Hides the little "Running..." man in the corner
gatherUsageStats = false
